version: '3.8'
services:
  frontend:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    container_name: server
    build:
      context: ./server
    ports:
      - "5000:5000"

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567    
      MYSQL_DATABASE: easyrice   
      MYSQL_USER: admin                    
      MYSQL_PASSWORD: 1234567                 
    ports:
      - "3306:3306"                                
    volumes:
      - db_data:/var/lib/mysql       

volumes:
  db_data: